use_frameworks!

target 'simpleel' do
  pod 'ELSwift', '1.0.0'

  post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['SWIFT_VERSION'] = '4.0'
          end
      end
  end
end

